### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lgmgeo**
Dear Jayne,

Please find additional information for the README.md file.

I hope you will find them useful.

Best regards,

Véronique

### CODE REVIEW

**Comment by lgmgeo** [comment]
The 2 updated files (20220530_alu_l1_herv_sva_GRCh3*_ucsc.rpmsk) are available at:
https://www.lbgi.fr/~geoffroy/Partage/Jayne/

**Comment by jyhehir** [comment]
contents of the pull request look fine. But please update it to point to the development branch so it will be included in an release, I would also prefer the files to be included as an update to the resources directory.

Thanks for your input!

**Comment by lgmgeo** [comment]
- No problem to update my pull request to point to the development branch. But which one?
image
- The 2 updated files are too big to be included as an update to the resources directory. That's why I put them available on a ftp site : https://www.lbgi.fr/~geoffroy/Partage/Jayne/

**Comment by jyhehir** [comment]
sorry for the confusion I meant the branch "develop".

**Pull request merged**
